### ISSUE TITLE
Does this require a command to work?

### ISSUE THREAD

**Issue by GambetTV** [gsimon2/hide-player-ui#1]
I'm not sure if it's just the limited documentation information here or if it's just not working, but as far as I can tell this doesn't do anything, even when it's the only module running. Is there a special way to activate it?

**Comment by gsimon2** [comment]
Sorry you are experiencing issues. I looked back over the code and had a small dependency on the PF2E system. As of version 1.0.3 this dependency has been removed. Please update the module and try the new version. Note that on the GM screen, you will not see any changes, only the player screen will have the control UI removed.

If you are still experiencing issues, please follow up here and we can work through them. Thanks for posting!
