### ISSUE TITLE
[Feature Request] User-level settings

### ISSUE THREAD

**Issue by supernovajm** [gsimon2/hide-player-ui#13]
First of all thanks for maintaining this!

I use this module for our twitch stream (Horizons Unknown). In addition to the base settings set by the GM, I would like for individual users to be able to set additional elements that they would like to hide (for obvious reasons they shouldn't be allowed to unhide elements that the GM has set.)

In our personal use-case: we have a tabletop user that we use for the map feed to twitch. That user has almost all elements hidden. But we would like to give other players the option of hiding the "active players" list

**Comment by gsimon2** [comment]
Hey @supernovajm, sounds like a fun use case to solve. I will add it to my to do list. Feel free to post your twitch username and maybe I'll hop in for a stream!

**Comment by supernovajm** [comment]
> Hey @supernovajm, sounds like a fun use case to solve. I will add it to my to do list. Feel free to post your twitch username and maybe I'll hop in for a stream!

Thanks! https://twitch.tv/hexgridheroes

**Comment by gsimon2** [comment]
@supernovajm  Please try out version `1.4.0` and let me know what you think. If there is anything else that would help, feel free to open another issue and I will see what I can do.

Good luck with your stream and thanks for posting!

**Comment by supernovajm** [comment]
Just tested, works exactly as I would have hoped! Thanks so much for adding this!
