### ISSUE TITLE
Only hides default UI

### ISSUE THREAD

**Issue by GambetTV** [gsimon2/hide-player-ui#2]
This is probably to be expected, but just as a heads up, if you're using the modules "Custom Hotbar" or "Token Action HUD" it won't remove those from the UI. Also, totally understandable if this is beyond the scope of this module, but if there's a way to only remove certain parts of the UI, or only remove it from a specific player rather than all players, that'd be awesome!

**Comment by gsimon2** [comment]
Noted. It will be kind of whack-a-mole for covering any UI added by specific modules, but when I get a chance I can look into supporting those two.

As for making the UI or player list more selective, that is a bit more work as I would have to build out some menu UI to make the actual the selection, but I can add it to a feature list for this module and look into tackling it down the road.

Thanks for posting!

**Comment by gsimon2** [comment]
Sorry for the delay, but I have finally gotten time to address all of the desired functionality in your original comment. Please download version 1.1.0 and try it out. Thanks for posting!
