### ISSUE TITLE
Fix sidebar being right aligned rather than evenly spaced

### ISSUE THREAD

**Issue by nicholassaylor** [gsimon2/hide-player-ui#21]
Current behavior:
Expanded sidebar tabs are right-aligned causing an ugly underhang effect

Expected behavior:
Expanded sidebar tabs are evenly-spaced causing tabs to take up more space to prevent bunching the right corner

Current workaround:
Using [custom-css](https://github.com/cswendrowski/FoundryVTT-Custom-CSS), the user can put the following css in to fix the issue:
`
nav#sidebar-tabs.tabs {
     justify-content: space-evenly;
}
`

Possible fix:
Edit/override the stylesheet for foundry in order to correct the justification for the tabs in the sidebar

**Comment by nicholassaylor** [comment]
Fixed in pull request #22

**Comment by gsimon2** [comment]
Thanks for submitting a PR for this fix. I apologize for the long delay, took most of the summer off. 

This is included in the just released 1.5.1 version.
