### ISSUE TITLE
Hiding the Foundry Logo make the "Controls" and "Navigation Section" overlap.

### ISSUE THREAD

**Issue by KelSolaar** [gsimon2/hide-player-ui#24]
Hello,

As I was testing this module I noticed that hiding the Foundry Logo make the "Controls" and "Navigation Section" overlap:

![image](https://user-images.githubusercontent.com/99779/210728103-c2db0a60-8a5b-4f48-9a33-a68a7a411913.png)

Note that I have also the "Players" and "Macro Bar" UI elements hidden.

Cheers,

Thomas

**Comment by gsimon2** [comment]
Thanks for reporting the bug!

When I get time I will look into it and let you know when a fix is released.

**Comment by gsimon2** [comment]
This should be fixed in version `1.5.2` of the module. Thanks for the callout!
