### ISSUE TITLE
Won't hide PF2e logo when used with pf2e system and Pathfinder Ui v3

### ISSUE THREAD

**Issue by ksignorini** [gsimon2/hide-player-ui#28]
When used with PF2e system and the Pathfinder Ui v3 module (which replaces the standard Foundry corner logo with a Pathfinder specific one) Hide Player UI won't hide the Pathfinder logo on player screens.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/6867660/215517099-95520d1c-f6d3-44d3-9866-9c312a921e4b.png">

**Comment by gsimon2** [comment]
This should be fixed in version `1.5.3`. Give it a try and let me know if you have any issues!
