### ISSUE TITLE
Error: You are accessing the User#data object which is no longer used

### ISSUE THREAD

**Issue by mrjaksauce** [gsimon2/hide-player-ui#31]
![image](https://user-images.githubusercontent.com/68178310/222978675-1a49f93f-c558-4d77-bd4b-46b7ee96531f.png)

**Comment by mrjaksauce** [comment]
This could be a libwrapper error: 
![image](https://user-images.githubusercontent.com/68178310/222978843-01a749f6-a0d5-47bc-a99d-a5176ef8e4ab.png)

**Comment by gsimon2** [comment]
Thanks for bringing this to my attention!

The warning should be fixed as of version `1.5.4`
