### ISSUE TITLE
Request: Hide only the chat input box

### ISSUE THREAD

**Issue by halfd0rk** [gsimon2/hide-player-ui#33]
I'd love to still have the chat log of rolls, but hide the large input field that is at the bottom of the chat.

**Comment by gsimon2** [comment]
@halfd0rk Thanks for the suggestion! I have added the functionality to the main branch. I am going to try to add a few more features before cutting a new release but I should roll one out in a week or two that will support hiding the chat input field.

**Comment by gsimon2** [comment]
This functionality is now added in version 1.7.0. Please let me know if you have any issues or suggestions!
