### ISSUE TITLE
Issue: Changing "Personal" settings affects multiple accounts when using the same browser

### ISSUE THREAD

**Issue by halfd0rk** [gsimon2/hide-player-ui#34]
I was trying to hide my "Party Chat" character's UI. When I attempted to alter only the Party Chat UI from either the GM account, or through the personal settings of the Party Chat account; it alters both accounts. What made things more difficult was not being able to access the game settings from a disabled ui.

This most likely has something to do with using the same browser/cache? After logging into the user Party Chat from a different browser it seemed to be working as intended. I then made all my ui changes, saved, reopened in chrome and everything was applied. I stream using two chrome windows, as certain modules work best with chrome so this was a confusing troubleshoot.

Just reporting my bug encounter, though I think this was a browser/cache issue for me.

**Comment by gsimon2** [comment]
Hey @halfd0rk ,

Yea using the same browser for multiple users will probably be subject to small settings being shared. Currently the personal settings are saving the setting with the client scope, which from the Foundry documentation:

>Client Settings are saved in the browser and apply to all Worlds that are accessed from the same device using the same browser. Maximum Framerate and Performance Modes are examples of a client setting. Any user, regardless of permission, can modify their own client-level settings.

While they don't explicitly say that these settings are shared between users, I highly suspect that they are. 

A possible future work around would be to use the GM account to hide connecting player's UI and then add the "Party Chat" name to the "Player Names with Hidden UI" option.

![image](https://user-images.githubusercontent.com/20954654/226781635-e42479a3-f10d-40e3-ba3e-c219c9dc6cad.png)

Glad you found a way around it. If I have time I will dig more into the client settings scope and see if there is a way to make it unique to a user.

**Comment by gsimon2** [comment]
Hey @halfd0rk ,

This issue should be fixed as of version `1.6.0` of the module. User settings are now being stored as a flag on the user document rather then on the client scope.

Thanks for reporting the issue!
