### ISSUE TITLE
Question -> Request: Game setting specification

### ISSUE THREAD

**Issue by Weskernation** [gsimon2/hide-player-ui#35]
Would it be possible when hiding the "Game setting" to select what settings are hidden.
Like, If we want the players to be able to change settings in ONLY the Core but hide all the others (mods).

is this possible?

- When hiding all, players cannot change their Language (circumstantial), Performance Mode, Font Size, etc etc. Basically the things I do not want to necessarily block.

**Comment by gsimon2** [comment]
This functionality is now added in version 1.7.0. You can now add a list of elements you want to hide (identified by their CSS selectors) and add them to the either your personal configuration or the settings for connecting players. 

Please let me know if you have any issues or suggestions!
