### ISSUE TITLE
Foundry V11 compatibility

### ISSUE THREAD

**Issue by nschoenwald** [gsimon2/hide-player-ui#37]
The module currently does not work in V11. An update would be great, if possible!

**Comment by coffiarts** [comment]
Are you referring to the fact that it hasn't been _declared_ yet as v11 compatible, or have you encountered specific issues with v11? I've just run some quick tests in my v11 install, and it seems to work pretty well. So I guess (let's say: hope) that it is already compatible?

**Comment by nschoenwald** [comment]
For me, it does not work in V11. The elements I selected in settings do not
get hidden. I can do some further testing later if you can not reproduce
the problem and send you a screen recording if it helps.

coffiarts ***@***.***> schrieb am So., 25. Juni 2023, 16:24:

**Comment by nschoenwald** [comment]
Huh, strange, it works now! When I first tried it after upgrading, it didn't.
But I guess it just needs to have the compatibility in the manifest updated then.

**Comment by coffiarts** [comment]
Sounds good! Guess it's not a big thing, I'm eager to jump in and try to update it with a pull request. But I see that another one has been open since May (https://github.com/gsimon2/hide-player-ui/pull/36). So I assume that pull requests don't have a big chance right now to get merged?

**Comment by coffiarts** [comment]
Here's the pull request: https://github.com/gsimon2/hide-player-ui/pull/38
Was as simple as hoped (nothing but updates to the module.json). Let's hope that it gets merged, so that auto-installing/auto-updating from within FoundryVTT setup works again.

**Comment by gsimon2** [comment]
Sorry for the delay on this. 

Thanks for testing on v11. I have been behind with updating to the new major release.

**Comment by gsimon2** [comment]
Just released version `1.5.5` which updates the compatibility for version 11. Thanks for the PR!

**Comment by coffiarts** [comment]
Thanks for merging!
