### ISSUE TITLE
Add global Default GM settings

### ISSUE THREAD

**Issue by Zarhog** [gsimon2/hide-player-ui#39]
Hello i run a server with about 10 GMs and i would like to request the addition of Global GM and trial GM defalts as i would like to insure that all my Gms see the same UI and not have to set them up indevidualy

**Comment by gsimon2** [comment]
You can accomplish this by leveraging the "Player names with hidden UI` setting. This setting applies the "Connecting players UI configuration" to any of the players that you specify.

For example, if I wanted to apply hidden UI for only `Tester 1` and `Tester 2` but leave the default UI for everyone else I would apply the following settings (Note to uncheck "Hide for all players").

![image](https://github.com/gsimon2/hide-player-ui/assets/20954654/75c788c9-b069-47c8-84c9-ea98ba9c50f4)
