### ISSUE TITLE
[SUGGESTION] Option to select what is hidden

### ISSUE THREAD

**Issue by QuantumFunks** [gsimon2/hide-player-ui#4]
Is it possible to add an option into the settings for the module that let you tick boxes for each element you want hidden? Im keen to hide the tools, hotbar and navbar but the chat window is something id like my tabletop players to see when they roll their attacks.

**Comment by gsimon2** [comment]
I have just added this functionality. Please download version 1.1.0 and try it out. Thanks for posting!
