### ISSUE TITLE
Request 1: Add "Hide Scenes" to personal options

### ISSUE THREAD

**Issue by Zarhog** [gsimon2/hide-player-ui#44]
Features Request: Hide Scenes
I often find my self using this to reduce my UI so i can focus on a task, honestly i would love it if i could have a button in settings where i can quickly access this modals settings. so i can quickly reduce or increase my UI options

there appears to be no option to hide scenes and this may be required in some games where the VTT is just being used for character sheets and it is not needed but in my case i just want to hide it temporarily for workflow

**Comment by gsimon2** [comment]
This functionality has been added in version `1.6.0` of the module. Please let me know if you have any other suggestions.

Thanks for posting!
