### ISSUE TITLE
UI vanished

### ISSUE THREAD

**Issue by TheTenk** [gsimon2/hide-player-ui#46]
I tried to open the settings of this module after activating it and the menu was barebones, then the entirety of my ui just disappears irrevocably. Only fix is removing the module.

**Comment by gsimon2** [comment]
Is this for the GM or for a connecting player? What UI were you trying to hide?

Also please open the dev console and provide any errors that seem relevant when you try to start with just the `hide-player-ui` module active.

**Comment by Magicfairy2706** [comment]
Same here. Log in as GM and no UI. I don't know what to do. Only uninstall the module helped. After reinstall the UI is still vanished.

**Comment by JateaRH** [comment]
I'm also noticing a similar issue, Foundry 12, build 330, using the latest version of hide player UI (1.7.0?); on further investigation this might have something to do with how the settings are set up? I noticed this after updating Foundry from I think build 328?

Only active modules are this one (Hide Player UI) and Ready To Use Cards 1.13.1. (Temporarily disabling "Ready To Use Cards" did not resolve the issue.)

When I connected to my server as a player, the entire UI seems to have been hidden (except for the Cards module in use).

![image](https://github.com/user-attachments/assets/afed247d-1acc-4632-9b95-3fde89f39f0f)

I checked the player settings and found that every checkbox had been set to "on" (which meant that every UI element was being hidden for the players).

![image](https://github.com/user-attachments/assets/ec3ec473-af47-4a47-9897-c706016e06db)

Maybe the Personal UI Configuration is somehow defaulting to turning on all the options for some people?

**Comment by Toawi** [comment]
I´ve found a solution for this annoying problem.

1. Uninstall the hide-player-ui
2. install and activate forien-copy-environment
3. Export Settings
4. open the created json file
5. search for "name": "Gamemaster"
6. scroll down to the next "hide-player-ui"
7. set all entries to "true"
8. install hide-player-ui again and it should work

https://foundryvtt.com/packages/forien-copy-environment/

**Comment by joelplourde4** [comment]
Hey folks! 

I've ran into the same issue, I cannot enforce the author to review, approve & merge my pull request but in the meanwhile here's the way to fix it permanently:

1. Navigate to the module folders (I am on Windows so it looks like):
`C:\Users\User\AppData\Local\FoundryVTT\Data\modules\hide-player-ui\scripts`
2. Open the isGM.js
3. Copy & paste the code in the following Pull Request: https://github.com/gsimon2/hide-player-ui/pull/57/files
4. Enjoy!

**Comment by gsimon2** [comment]
Sorry for the delay on this and thanks to @joelplourde4  for creating a PR.

I could not reproduce the issue locally but the code changes make sense to me. Please try version `1.7.1` of the module and let me know if it resolves the issues you are facing.

Thanks!
