### ISSUE TITLE
Module Incompatibility with Foundry VTT Version 12

### ISSUE THREAD

**Issue by Niclasp1501** [gsimon2/hide-player-ui#50]
I have encountered an issue with the module, which does not function properly with the latest Foundry update. The module was working perfectly in previous versions but appears to be incompatible with the latest version.

**Comment by gsimon2** [comment]
@Niclasp1501  Please update the module to version `1.7.1`. If you are still experiencing issues please open another issue detailing what you are encountering. Closing this issue as it is pretty stale. Thanks!
