### ISSUE TITLE
Can you please add an option to hide UI eliments by Eliment ID 

### ISSUE THREAD

**Issue by Zarhog** [gsimon2/hide-player-ui#51]
below is an example macro for extending the hide UI to spcific UI eliments by Eliment ID

// Define the list of UI elements to target
let elementsToTarget = [
    "#settings-access > button:nth-child(3)", 
    "#settings-access > button:nth-child(1)", 
    "#settings-documentation > button:nth-child(3)",
    "#settings-documentation > button:nth-child(2)",
    "#settings-documentation > button:nth-child(1)",
    "#settings-game > button:nth-child(6)",
    "#settings-game > button:nth-child(4)",
    "#menu-items > li.menu-world",
    "#settings > h2:nth-child(7)",
    "a[data-tab='cards']",
    "a[data-tab='tables']",
    "a[data-tab='playlists']",
    "[data-folder-id='56NncOVH9UVNyxfU']", 
    "[data-folder-id='yc9aspl80BItriwG']", 
    "[data-folder-id='IryYZrM4mEhtbPLd']", 
    "[data-folder-id='guWiRx1RFD2JWe3D']", 
    "#items .create-folder", 
    "[data-folder-id='yS7GLrnhDdHvCmNG']", 
    "[data-folder-id='Mkx1SuLHybe6U9JK']", 
    "[data-folder-id='L1s6VSELdEBKcVcJ']",
    "#actors .create-folder",
    "#compendium .ic-wide.import-compendium",
    "a[data-tab='combat']",
    "#players > h3", 
    "#compendium .create-folder",
    "#compendium .create-entry",
    "#journal .create-folder",
    "#scenes .create-entry",
    "#client-settings > section > div > aside > div",
    "#notifications > li",
];

// Function to disable and hide UI element
function disableAndHideUIElement(selector) {
    let uiElement = document.querySelector(selector);
    if (uiElement) {
        uiElement.setAttribute('disabled', 'disabled');
        uiElement.style.display = 'none';
    }
}

// Function to observe changes in the UI elements
function observeUIElements(elements) {
    const observer = new MutationObserver(function(mutations) {
        mutations.forEach(function(mutation) {
            if (mutation.type === 'childList' || mutation.type === 'attributes') {
                let targetElement = elements.find(element => mutation.target.matches(element));
                if (targetElement) {
                    setTimeout(() => disableAndHideUIElement(targetElement), 50);
                }
            }
        });
    });

    elements.forEach(function(selector) {
        let uiElement = document.querySelector(selector);
        if (uiElement) {
            observer.observe(uiElement, { attributes: true, childList: true, subtree: true });
        }
    });
}

// Call the function with the elements to observe
observeUIElements(elementsToTarget);

// Initial sweep to disable and hide all the targeted UI elements
elementsToTarget.forEach(selector => disableAndHideUIElement(selector));

// Set up a periodic check every 1 seconds
setInterval(() => {
    elementsToTarget.forEach(selector => disableAndHideUIElement(selector));
}, 1000);

**Comment by gsimon2** [comment]
I may be able to something like this, but want to do some playing around with it first. 

I'll add it to my todo list. May be a few weeks before I can look into it.

**Comment by Zarhog** [comment]
Awesome 👍 thx man. I will note that my code is a little janky. So
apologies ahead of time 🙏. For stuff like the side bar on the left you may
need to add an observer. There is another modual which honestly I think
would be amazing if we could combine with yours. I'll search it out later

**Comment by gsimon2** [comment]
This functionality is now added in version `1.7.0`. Please let me know if you have any issues or suggestions!

**Comment by gsimon2** [comment]
This functionality is now added in version 1.7.0. Please let me know if you have any issues or suggestions!
