### ISSUE TITLE
Refreshing & New Scene Activation revealing pieces of the UI

### ISSUE THREAD

**Issue by CaptainRoBear** [gsimon2/hide-player-ui#6]
![hide ui upon main game refresh](https://user-images.githubusercontent.com/81845234/113495062-4524dd00-94b4-11eb-8058-7992456f50c5.png)
![hide ui upon scene change](https://user-images.githubusercontent.com/81845234/113495063-45bd7380-94b4-11eb-9879-130e7b786a66.png)

If I have to refresh the main game It begins revealing elements on the left side of the screen. If I activate a new scene elements on the the bottom left hand player menu reveal themselves. This was done with the intent of having only the sidebar element viewable. (Chrome Browser)

**Comment by gsimon2** [comment]
Sorry you are experiencing issues. Took a quick look and think I caused this in my last update. Will set aside some time this week to get it fixed. Thanks for the callout!

**Comment by CaptainRoBear** [comment]
You're welcome. This is the first time I've used Github in this capacity, very cool. Thanks for creating a super helpful module for us creators!

**Comment by gsimon2** [comment]
@CaptainRoBear  This should be fixed now in version 1.1.1. Please try it out and let me know if you experience any more issues. Thanks for posting!

**Comment by CaptainRoBear** [comment]
1.1.1 is looking good! Thank you!
