### ISSUE TITLE
Hello, ive ran into an issue with one of my items in my list, full list below

### ISSUE THREAD

**Issue by Zarhog** [gsimon2/hide-player-ui#61]
Full list
#client-settings > section > div > aside > div;
document.querySelector("#menu-items > li.menu-world");
#menu-items > li.menu-players;
#menu-items > li.menu-world;
#journal > header > div.ve-flex-col.dir__wrp-header.w-100.no-shrink.min-w-100.dir__control-header;
#actors > header > div.ve-flex-col.dir__wrp-header.w-100.no-shrink.min-w-100.dir__control-header;
#scenes > header > div.ve-flex-col.dir__wrp-header.w-100.no-shrink.min-w-100.dir__control-header;
#compendium > header > div.ve-flex-col.dir__wrp-header.w-100.no-shrink.min-w-100.dir__control-header.pb-1;
[data-control='effects'];
[data-control='objects-interactions-fx'];
[data-tool='clear'];
[data-tool='clone'];
[data-tool='showurl'];
[data-control='tiles'];
[data-tool='select'];
[data-control='sounds'];
[data-tool='convenient-effects'];
[data-tool='stealthy-perception-toggle'];
[data-tool='snap'];
#players > h3;
#scenes > header > div.header-actions.action-buttons.flexrow > button.create-folder;
[data-folder-id='PiB2LGEOoA6h7iXm'];
[data-folder-id='cvxyXP2s0dSYTix4'];
#actors > header > div.header-actions.action-buttons.flexrow > button.create-folder;
[id^="UserConfig-User"] > fieldset:nth-child(1) {display: none;}

Issue item
[id^="UserConfig-User"] > fieldset:nth-child(1) {display: none;}

^ this works on a normal CSS editor, but fails to work in this modual. even with at ; after ite for the list fixing. i belive the problem is that it includes ; after none, unsure how to fix this

**Comment by Zarhog** [comment]
![image](https://github.com/user-attachments/assets/ef270390-3df2-4461-a52e-75de0e5107f3)


for reference we are trying to remove this section for all player "Player information"
as we consider it bloat. and not needed. we only need the "Player Character" Section

**Comment by gsimon2** [comment]
Have you tried adding the just the selector? Not sure why you have the style block `{display: none;}` included.

Try just ```[id^="UserConfig-User"] > fieldset:nth-child(1);```

**Comment by gsimon2** [comment]
You can also try
```[id^="UserConfig-User"] > fieldset:first-child;```

**Comment by Zarhog** [comment]
thx a lot :)
